name: Trivy Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trivy:
    name: Run Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

      - name: Scan Python dependencies (SCA)
        run: trivy fs --scanners vuln . --exit-code 1 --severity HIGH,CRITICAL

      - name: Scan for secrets
        run: trivy fs --scanners secret . --exit-code 1

      - name: Scan Dockerfile and configs (CA/SAST)
        run: trivy config . --exit-code 0
